server:
  port: 9001

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 200MB
  datasource:
    url: jdbc:mysql://115.29.242.80:3306/bankwel_phjf?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: phjf_test
    password: phjf_test
    driver-class-name: com.mysql.cj.jdbc.Driver

